server:
  port: 8671
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id : ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path= /admin/**


        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /user/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka